# Generated by Django 5.1.3 on 2024-12-07 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='meeting',
            name='patient_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='browser.patient'),
        ),
    ]
